### ISSUE TITLE
Error with Certain Files

### ISSUE THREAD

**Issue by Chazza** [Claviz/xlstream#29]
Hi team,

Firstly thank you lots for building this, it's been extremely useful within my workplace to quickly extract data from worksheets. I'm having an issue that seems to happen with random excel files, and I'm not sure why.

```
charlie@charlies-mbp ClaimScraper % node scrape.js                                                          
 
=============================================
 Claim Scraper
=============================================
 
Preparing to scrape..
(node:1774) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'relsId' of undefined
    at /Users/charlie/Downloads/ClaimScraper/node_modules/xlstream/lib/index.js:444:77
    at step (/Users/charlie/Downloads/ClaimScraper/node_modules/xlstream/lib/index.js:33:23)
    at Object.next (/Users/charlie/Downloads/ClaimScraper/node_modules/xlstream/lib/index.js:14:53)
    at step (/Users/charlie/Downloads/ClaimScraper/node_modules/xlstream/lib/index.js:18:139)
    at Object.next (/Users/charlie/Downloads/ClaimScraper/node_modules/xlstream/lib/index.js:14:53)
    at resume (/Users/charlie/Downloads/ClaimScraper/node_modules/xlstream/lib/index.js:44:44)
    at fulfill (/Users/charlie/Downloads/ClaimScraper/node_modules/xlstream/lib/index.js:46:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1774) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1774) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
charlie@charlies-mbp ClaimScraper % 
```

What is the cause of this?

**Comment by jansivans** [comment]
Hi.
Thank you for kind words.
Can you provide XSLX file so I can reproduce it?

**Comment by Chazza** [comment]
Hi,

Sadly can't distribute because of GDPR reasons, is there any testing or debugging you can add so I can try?

**Comment by jansivans** [comment]
Seems like a problem with sheets parsing.
Can you remove all data (leave blank sheets) and send this file?

**Comment by Chazza** [comment]
Ok, apologies - it seemed updating to the latest version fixed this (I hope!). Will close this and comment back if I face more issues in future :)

**Comment by jansivans** [comment]
How your excel files were generated?
If using OpenXML library (C#) then yes, it was fixed last time.

**Comment by Chazza** [comment]
We received these from a third party (as its insurance claims), so I'm not sure but I could only guess so.
