### ISSUE TITLE
GetWorksheets doesn't handle errors correctly

### ISSUE THREAD

**Issue by santiq** [Claviz/xlstream#31]
Hello again

The function `getWorksheets` doesn't handle errors correctly if I try to process a corrupted xlsx file.

I look into the code and I think `reject` should be called on stream.on('error') or zip callback with err.

```js
getWorksheets(options: IWorksheetOptions) {
    return new Promise<IWorksheet[]>((resolve, reject) => {
        function processWorkbook() {
            zip.stream('xl/workbook.xml', (err: any, stream: ReadStream) => {

               // Here
               if (err) {
                return reject(err);
               }

                stream.pipe(saxStream({
                    strict: true,
                    tag: ['x:sheet', 'sheet'],
                })).on('data', (x: any) => {
                    sheets.push({
                        name: x.record.attribs.name,
                        hidden: x.record.attribs.state && x.record.attribs.state === 'hidden' ? true : false,
                    });
                });
                // Here
                stream.on('error', reject);

                stream.on('end', () => {
                    zip.close();
                    resolve(sheets);
                });
            });
        }

        let sheets: IWorksheet[] = [];
        const zip = new StreamZip({
            file: options.filePath,
            storeEntries: true,
        });
        zip.on('ready', () => {
            processWorkbook();
        });
    });
}
```

My error stack: 

```
[14:40:07] [ERROR] Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Bad archive')
    at StreamZip.emit (events.js:304:17)
    at StreamZip.EventEmitter.emit (domain.js:482:12)
    at StreamZip.emit (/var/www/my-app/node_modules/node-stream-zip/node_stream_zip.js:598:33)
    at FsRead.readUntilFoundCallback [as callback] (/var/www/my-app/node_modules/node-stream-zip/node_stream_zip.js:201:25)
    at FsRead.readCallback (/var/www/my-app/node_modules/node-stream-zip/node_stream_zip.js:869:21)
    at FSReqCallback.wrapper [as oncomplete] (fs.js:516:5)

```

Edit: I tried to put a try/catch block on my call to getWorksheets but it doesn't work.

**Comment by santiq** [comment]
Actually, my problem was with the Streamzip instance, adding an error handler for the event emitter solved it.

```js
        let sheets: IWorksheet[] = [];
        const zip = new StreamZip({
            file: options.filePath,
            storeEntries: true,
        });
        zip.on('ready', () => {
            processWorkbook();
        });

      // Error Handler
       zip.on('error', reject) 
```

**Comment by jansivans** [comment]
Hi!
If you have a solution and wish to contribute, feel free to open PR.

**Comment by jansivans** [comment]
Sure.
Version 2.3.1 was published to NPM.
